name: Build and Release MasterRelayVPN

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (1.2.3)"
        required: true
      release_name:
        description: "Release v1.2.3"
        required: true
      release_body:
        description: "Release pp"
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore gui/MasterRelayVPN.csproj

      - name: Build Release
        run: dotnet publish gui/MasterRelayVPN.csproj -c Release -r win-x64 --self-contained true -o build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MasterRelayVPN
          path: build/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: MasterRelayVPN
          path: build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          name: ${{ github.event.inputs.release_name }}
          body: ${{ github.event.inputs.release_body }}
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
